### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by Jeremy-07** [liukun95/Noisy-NER-Confidence-Estimation#1]
Hello, your work is very interesting, but I still can't understand some parts of the article. I was wondering if you could share the code for us to learn, thank you.

**Comment by liukun95** [comment]
Hi,thanks for your intrest. We are preparing the code for open source, the code is coming soon.


------------------ Original ------------------
From: Jeremy-07 ***@***.***&gt;
Date: 周三,4月 21,2021 11:12 上午
To: liukun95/Noisy-NER-Confidence-Estimation ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [liukun95/Noisy-NER-Confidence-Estimation] Source Code (#1)





 
Hello, your work is very interesting, but I still can't understand some parts of the article. I was wondering if you could share the code for us to learn, thank you.

**Comment by Jeremy-07** [comment]
Thank you for your reply.
